; ---------------------------------------------------------------------------
;  installer.iss — Inno Setup script for Bunney POS (Windows)
;
;  Wraps dist\BunneyPOS.exe into a standard Windows installer:
;    BunneyPOS_v1.0.0_Setup.exe
;
;  What it does
;    * installs to            C:\Program Files\Bunney POS
;    * creates a desktop shortcut and a Start Menu entry
;    * registers an uninstaller ("إلغاء التثبيت") in Apps & Features
;    * offers an optional launch after install
;
;  Build it
;    1. Build the exe first (see windows_build.spec):
;         py -m venv .venv
;         .venv\Scripts\pip install -r requirements.txt pyinstaller
;         .venv\Scripts\pyinstaller --clean --noconfirm windows_build.spec
;    2. Install Inno Setup 6:  https://jrsoftware.org/isdl.php
;    3. Compile this script:
;         "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
;       or open installer.iss in the Inno Setup IDE and press F9.
;
;  Output: dist\BunneyPOS_v1.0.0_Setup.exe
;
;  IMPORTANT — where the data goes
;    The app writes its database, backups, receipts and logs to
;      %LOCALAPPDATA%\bunney-pos
;    It detects that Program Files is not writable and falls back there
;    automatically. Nothing is written into the install directory, so the
;    uninstaller never has to guess which files were user data.
; ---------------------------------------------------------------------------

#define MyAppName "Bunney POS"
#define MyAppNameAr "نظام بُنّي للنقاط البيع"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Bunney POS"
#define MyAppExeName "BunneyPOS.exe"
#define MyAppId "{{8F3A5C21-9B4E-4E7A-9C1D-2A6B7E5D4C30}"

[Setup]
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
VersionInfoVersion={#MyAppVersion}

; --- Password protection ---------------------------------------------------
; The installer will NOT proceed and will NOT extract any files until the
; correct password is entered. Encryption=yes is required for Password to work.
;
; The password is NOT stored in this file. It is read at compile time from:
;   1. The SETUP_PASSWORD environment variable, OR
;   2. A .env file in the project root (SETUP_PASSWORD=...)
;
; build-windows.bat handles both automatically. To set your own password:
;   - Windows: set SETUP_PASSWORD=your_password_here
;   - Or create a .env file with: SETUP_PASSWORD=your_password_here
;
; If neither is set, the build will fail with a clear error.
;
; {#SetupPassword} is resolved at compile time by build-windows.bat, which
; reads SETUP_PASSWORD from the environment or .env and passes it to ISCC
; via /D. The value never appears in this file.
#define SetupPassword GetEnv('SETUP_PASSWORD')
Password={#SetupPassword}
Encryption=yes

; Install into Program Files, which is what "standard desktop software" means
; to a user. Needs admin, hence PrivilegesRequired=admin below.
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
AllowNoIcons=no

; Output
OutputDir=dist
OutputBaseFilename=BunneyPOS_v{#MyAppVersion}_Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

; SetupIconFile needs a real .ico. The file is committed to the repo
; (assets\icons\logo.ico, generated by tools\make_icons.py), so this normally
; resolves. The guard keeps the build from failing outright if someone removes
; it, which would otherwise stop the whole installer with a confusing error.
#if FileExists(AddBackslash(SourcePath) + "assets\icons\logo.ico")
SetupIconFile=assets\icons\logo.ico
#endif

; Uninstaller naming — shown in Apps & Features.
UninstallDisplayName={#MyAppName} ({#MyAppNameAr})
UninstallDisplayIcon={app}\{#MyAppExeName}

; 64-bit only, matching the PyInstaller build.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

; Program Files needs elevation.
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=dialog

; Windows 10 and newer.
MinVersion=10.0

[Languages]
; Arabic is offered alongside English because that is the app's language.
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; \
    GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
; The single-file exe built by windows_build.spec.
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; Icon and licence alongside it, so the user can find them.
Source: "assets\icons\logo.ico"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist
Source: "assets\icons\logo.svg"; DestDir: "{app}"; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Start Menu entry.
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; \
    IconFilename: "{app}\logo.ico"; Comment: "{#MyAppNameAr}"
; Desktop shortcut (optional, ticked by default).
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; \
    IconFilename: "{app}\logo.ico"; Comment: "{#MyAppNameAr}"; Tasks: desktopicon

[Run]
; Offer to launch straight after install.
Filename: "{app}\{#MyAppExeName}"; \
    Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; \
    Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Nothing from the app itself lives here, but Qt and PyInstaller can leave
; caches behind. The user's data in %LOCALAPPDATA%\bunney-pos is deliberately
; NOT touched — see the note in [Code].
Type: filesandordirs; Name: "{app}\_internal"
Type: dirifempty; Name: "{app}"

[Code]
{ -------------------------------------------------------------------------
  Password resolution.

  The installer password is read at compile time from:
    1. The SETUP_PASSWORD environment variable, OR
    2. A .env file in the project root (SETUP_PASSWORD=...)

  build-windows.bat handles both. If neither is set, the build fails with
  a clear error before Inno Setup is invoked.
  ------------------------------------------------------------------------- }
function GetSetupPassword(): String;
var
  EnvValue: String;
  EnvFile: String;
  Lines: TArrayOfString;
  I: Integer;
  Line: String;
begin
  { 1. Environment variable }
  EnvValue := GetEnv('SETUP_PASSWORD');
  if EnvValue <> '' then
  begin
    Result := EnvValue;
    exit;
  end;

  { 2. .env file in the project root }
  EnvFile := ExpandConstant('{src}\.env');
  if FileExists(EnvFile) then
  begin
    if LoadStringsFromFile(EnvFile, Lines) then
    begin
      for I := 0 to GetArrayLength(Lines) - 1 do
      begin
        Line := Lines[I];
        if Pos('SETUP_PASSWORD=', Line) = 1 then
        begin
          Result := Copy(Line, Length('SETUP_PASSWORD=') + 1, Length(Line));
          { Trim whitespace }
          while (Length(Result) > 0) and ((Result[1] = ' ') or (Result[1] = #9)) do
            Result := Copy(Result, 2, Length(Result));
          while (Length(Result) > 0) and ((Result[Length(Result)] = ' ') or (Result[Length(Result)] = #9)) do
            Result := Copy(Result, 1, Length(Result) - 1);
          exit;
        end;
      end;
    end;
  end;

  { Neither found — return empty so the build fails with a clear error }
  Result := '';
end;

{ -------------------------------------------------------------------------
  On uninstall, ask whether to also delete the user's data.

  The database holds a cafe's entire sales history, so removing it silently
  would be unforgivable. Defaulting to "No" means the safe outcome needs no
  thought, and an operator who really wants a clean machine can say yes.
  ------------------------------------------------------------------------- }
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
  Response: Integer;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    DataDir := ExpandConstant('{localappdata}\bunney-pos');
    if DirExists(DataDir) then
    begin
      Response := MsgBox(
        'Also delete your Bunney POS data?' + #13#10 + #13#10 +
        'This permanently removes the database, backups, receipts and logs from:'
        + #13#10 + DataDir + #13#10 + #13#10 +
        'Choose No to keep your sales history (recommended).',
        mbConfirmation, MB_YESNO or MB_DEFBUTTON2);
      if Response = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
